"""init_todas_las_tablas

Revision ID: 30104ef9f745
Revises: 
Create Date: 2026-06-14 00:02:50.942277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30104ef9f745'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('faculties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_experience_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('first_day', 'friends', 'classes', 'teachers', 'exams', 'campus', 'clubs', 'tips', 'fears', name='experience_categoria_enum'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('local', 'google', name='provider_enum'), nullable=False),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('utp_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.Enum('laboratorios', 'convenios', 'empleabilidad', 'bienestar', 'tutorias', 'bolsa_laboral', 'internacional', name='utp_categoria_enum'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('faculty_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('descripcion_corta', sa.Text(), nullable=True),
    sa.Column('duracion_semestres', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.Enum('presencial', 'semi_presencial', 'virtual', name='modalidad_enum'), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('demanda_laboral', sa.Enum('alta', 'media', 'baja', name='demanda_enum'), nullable=False),
    sa.Column('trabajo_remoto', sa.Boolean(), nullable=False),
    sa.Column('salario_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_promedio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('vocational_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'abandoned', name='session_status_enum'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['comparison_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['vocational_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_rankings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['vocational_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_ranking_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('ranking_position', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interaction_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ai_justification', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['vocational_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_section_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('selected_career_id', sa.UUID(), nullable=False),
    sa.Column('score_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['comparison_sections.id'], ),
    sa.ForeignKeyConstraint(['selected_career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['vocational_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_selected_careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('selected_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['vocational_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatbot_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_messages')
    op.drop_table('session_selected_careers')
    op.drop_table('session_section_answers')
    op.drop_table('session_ranking_results')
    op.drop_table('saved_rankings')
    op.drop_table('chatbot_knowledge')
    op.drop_table('chatbot_conversations')
    op.drop_table('career_cards')
    op.drop_table('vocational_sessions')
    op.drop_table('careers')
    op.drop_table('utp_content')
    op.drop_table('users')
    op.drop_table('university_experience_content')
    op.drop_table('faculties')
    op.drop_table('comparison_sections')
    # ### end Alembic commands ###
